import cv2 as cv
from tqdm import tqdm
import random
import time
import sys
import os

from datasetMOT17 import ImgStream
from datasetMOT17 import dataset_train as dataset

USER_INPUT_LEN = 3
CONFIG = {
    'IMG_640x640': {
        'dir' : 'letterbox_640x640',
        'size' : 640
        },
    'IMG_480x480' : {
        'dir' : 'letterbox_480x480',
        'size' : 480
        }
} 

YOLO_DIRS = ['train', 'val', 'test']
ZERO_PADDING = [0, 0, 0]

def create_dest_path(src_path, tov, config):
    aux = src_path.split("/")
    aux[-1] = aux[-3] + aux[-1]     # File name
    aux[-4] = config['dir']         # root dir
    aux[-3] = 'images'              
    aux[-2] = tov                   # train, validation or test
    img_path = "/".join(aux)

    aux2 = aux[-1].split(".")
    aux2[-1] = "txt"
    aux[-1] = ".".join(aux2)
    aux[-2] = tov
    aux[-3] = 'labels'
    label_path = "/".join(aux)

    return img_path, label_path

def letterbox(ratio, config):
    yolo_sz = config['size']
    new_hw = int(yolo_sz / ratio)

    padding_pixels = yolo_sz - new_hw
    x = padding_pixels // 2
    y = x + padding_pixels % 2

    return yolo_sz, new_hw, x, y
    
def process_image(dst, src, config):
    img = cv.imread(src, cv.IMREAD_COLOR)
    
    h, w = img.shape[:2]
    ratio = w/h
    top = bottom = left = right = 0

    if ratio > 1:
        new_width, new_height, top, bottom = letterbox(ratio, config)
    else:
        new_height, new_width, left, right = letterbox(ratio, config)

    new_img = cv.resize(img, (new_width, new_height))
    new_img = cv.copyMakeBorder(new_img, 
                                top, 
                                bottom,
                                left, 
                                right, 
                                cv.BORDER_CONSTANT, 
                                value=ZERO_PADDING)
    cv.imwrite(dst, new_img)
    return h, w

def process_bbox(path, bbox, h, w):
    fd = open(path, 'w')

    for box in bbox:
        xc = box[0] + box[2] / 2.
        yc = box[1] + box[3] / 2.
        
        line = str(int(box[-1])) + ' ' + \
               str(xc / w)       + ' ' + \
               str(yc / h)       + ' ' + \
               str(box[2] / w)   + ' ' + \
               str(box[3] / h)   + '\n'
        fd.write(line)
    fd.close()

def flip_train_validation(total, train_len=0.8):
    if random.random() < train_len:
        return "train"

    return "val"
    
def process_dataset(dataset_path, config):
    stream = ImgStream(dataset_path)

    for bbox, src_path in stream.streamPath():
        tov = flip_train_validation(stream.frame_count)
        img_path, label_path = create_dest_path(src_path, tov, config)
        
        h, w = process_image(img_path, src_path, config)
        process_bbox(label_path, bbox, h, w)

def create_yaml(root_dir, config):
    path = root_dir + '/' + config['dir']

    yaml_content = \
"# YOLO Dataset Configuration for MOT17\n" \
"# Auto-generated by YoloFormatterMOT17\n" \
"# Author: C. Alvarado / ckevar\n" \
"# Date: " + time.asctime() + '\n' \
"#\n"\
"# Configuration:\n"\
"#   image_size: " + str(config['size']) + 'x' + str(config['size']) + '\n' \
"#   nc: 12\n"\
"#   path: It might need adjusted properly.\n" \
"\n"\
"path: " + path + '\n' + \
YOLO_DIRS[0] + ": images/" + YOLO_DIRS[0] + '\n' + \
YOLO_DIRS[1] + ": images/" + YOLO_DIRS[1] + '\n' + \
YOLO_DIRS[2] + ": images/" + YOLO_DIRS[2] + '\n' + \
"\n" \
"names:\n" \
"    0: Pedestrian\n" \
"    1: Person on vehicle\n" \
"    2: Car\n" \
"    3: Bicycle\n" \
"    4: Motorbike\n" \
"    5: Non motorized vehicle\n" \
"    6: Static person\n" \
"    7: Distractor\n" \
"    8: Occluder\n" \
"    9: Occluder on the ground\n" \
"    10: Occluder full\n" \
"    11: Reflection\n"

    fd = open(path + '/data.yaml', 'w')
    fd.write(yaml_content)
    fd.close()
    
def main(root_dir, config):

    for ds in tqdm(dataset):
        process_dataset(root_dir + '/' + ds, config)

    create_yaml(root_dir, config)

def _make_directory_(target_dir):
    try:
        os.makedirs(target_dir)
    except FileExistsError:
        pass
    except Exception as e:
        print("\n  Something went wrong when creating images dir.", e)
        exit()

def mkdirs(root_dir, out_dir):
    images_dir = root_dir + '/' + out_dir + '/images'
    labels_dir = root_dir + '/' + out_dir + '/labels'
    for yd in YOLO_DIRS:
        _make_directory_(images_dir + '/' + yd)
        _make_directory_(labels_dir + '/' + yd)
 
def init(root_dir, config):
    random.seed(time.time())
    mkdirs(root_dir, config['dir'])

def parse_user_input(argv):
    configs = list(CONFIG.keys())
    if (len(argv) < USER_INPUT_LEN) or (argv[2] not in configs):
        print("\nusage: python3 {} <dir> <imgsz>\n"\
              "  dir   : directory of MOT-17 dataset\n"\
              "  imgsz : {}".format(argv[0], configs))
        exit()

    return argv[1], CONFIG[argv[2]]

if "__main__" == __name__:
    root_dir, config = parse_user_input(sys.argv)

    init(root_dir, config)
    main(root_dir, config)

